'use server';
/**
 * @fileOverview An AI agent for verifying payment receipts and shared screenshots.
 *
 * - verifyPayment - A function that takes a screenshot/receipt and expected payment details.
 * - VerifyPaymentInput - The input type for the verifyPayment function.
 * - VerifyPaymentOutput - The return type for the verifyPayment function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const VerifyPaymentInputSchema = z.object({
  screenshotDataUri: z
    .string()
    .describe(
      "The payment receipt or screenshot as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  expectedAmount: z.number().describe("The expected numerical amount paid."),
  expectedCurrency: z.string().describe("The expected currency code (e.g., 'INR', 'USD')."),
  expectedRecipientUpi: z.string().describe("The specific UPI ID that should have received the payment."),
});
export type VerifyPaymentInput = z.infer<typeof VerifyPaymentInputSchema>;

const VerifyPaymentOutputSchema = z.object({
  isValid: z.boolean().describe("True if the payment is verified as successful, matches all expected details, and appears to be an authentic receipt or non-doctored screenshot."),
  reason: z.string().optional().describe("A clear explanation of why the verification failed, specifically mentioning if the recipient, amount, or authenticity was the issue."),
  detectedAmount: z.number().optional().describe("The numerical amount detected in the screenshot."),
  detectedCurrency: z.string().optional().describe("The currency code detected in the screenshot."),
  detectedRecipient: z.string().optional().describe("The recipient address or UPI ID detected in the screenshot."),
  detectedDate: z.string().optional().describe("The date of the transaction detected in the screenshot."),
  isDoctored: z.boolean().optional().describe("Whether the AI suspects the image has been edited or is a known fake template."),
});
export type VerifyPaymentOutput = z.infer<typeof VerifyPaymentOutputSchema>;

const verifyPaymentPrompt = ai.definePrompt({
  name: 'verifyPaymentPrompt',
  input: { schema: VerifyPaymentInputSchema },
  output: { schema: VerifyPaymentOutputSchema },
  prompt: `You are a meticulous financial auditor for TeachMeet. Your primary goal is to prevent fraud and ensure that users have made a legitimate payment to the platform.

**Your Task:**
Analyze the provided payment evidence (could be a device screenshot or a "Shared Receipt" image from a payment app) and determine if it represents a valid, successful transaction that meets all criteria.

**Verification Criteria:**
1. **Authenticity Check**: Examine the image for signs of editing or doctoring. Note that "Shared Receipts" (images generated by clicking 'Share' in GPay/PhonePe) often look cleaner and more professional than raw screenshots.
2. **Recipient Match**: The payment MUST be addressed to exactly: "{{expectedRecipientUpi}}". Check the UPI ID, handle, or name associated with this address.
3. **Amount Match**: The detected amount must be exactly {{expectedAmount}}.
4. **Currency Match**: The detected currency must match {{expectedCurrency}}.
5. **Status Check**: The transaction must show as "Success", "Completed", "Paid", or similar. Pending or failed transactions are invalid.
6. **Recent Date**: The date must be very recent (ideally today or within the last 24 hours).

**Evidence Image:**
{{media url=screenshotDataUri}}

**Instructions:**
- If the image looks like a suspicious fake or inconsistent template, set isDoctored to true and isValid to false.
- If the recipient does not match {{expectedRecipientUpi}}, set isValid to false and explain that the payment was sent to the wrong address.
- Be understanding of "Shared Receipt" formats which are common when users cannot take direct screenshots.
- Provide a detailed reason for any failure to help the user correct their mistake.`,
});

const verifyPaymentFlow = ai.defineFlow(
  {
    name: 'verifyPaymentFlow',
    inputSchema: VerifyPaymentInputSchema,
    outputSchema: VerifyPaymentOutputSchema,
  },
  async input => {
    const response = await verifyPaymentPrompt(input);
    return response.output!;
  }
);

export async function verifyPayment(input: VerifyPaymentInput): Promise<VerifyPaymentOutput> {
  return verifyPaymentFlow(input);
}
