
// A list of common disposable email domains.
// This is not exhaustive but covers many popular services.
export const disposableEmailDomains = [
  '0-mail.com', '027168.com', '0815.ru', '0clickemail.com', '0wnd.net', '0wnd.org', 
  '10minutemail.co.za', '10minutemail.com', '123-m.com', '1fsdfdsfsdf.tk', '1pad.de', 
  '20minutemail.com', '21cn.com', '2fdgdfgdfgdf.tk', '2prong.com', '30minutemail.com', 
  '33mail.com', '3trtretgfrfe.tk', '4gfdsgfdgfd.tk', '4warding.com', '5ghgfhfghfgh.tk', 
  '6hjgkighjkgh.tk', '6paq.com', '7tags.com', '9ox.net', 'a-bc.net', 'afrobacon.com', 
  'ajaxapp.net', 'amilegit.com', 'amiri.net', 'amiriindustries.com', 'anonbox.net', 
  'anonymbox.com', 'antichef.com', 'antichef.net', 'antispam.de', 'antispam24.de', 
  'armyspy.com', 'artman-conception.com', 'azmeil.tk', 'baxomale.ht.cx', 'beefmilk.com', 
  'binkmail.com', 'bio-muesli.net', 'bobmail.info', 'bodhi.bt', 'bofthew.com', 'bootybay.de', 
  'boun.cr', 'bouncr.com', 'breakthru.com', 'brefmail.com', 'bsnow.net', 'bspamfree.org', 
  'bugmenot.com', 'bumpymail.com', 'bund.us', 'burstmail.info', 'buymoreplays.com', 
  'byom.de', 'c2.hu', 'card.zp.ua', 'casualdx.com', 'cek.pm', 'centermail.com', 
  'centermail.net', 'chammy.info', 'childsavetube.org', 'chogmail.com', 'choicemail1.com', 
  'clixser.com', 'cmail.net', 'cmail.org', 'coldemail.info', 'cool.fr.nf', 'courriel.fr.nf', 
  'courrieltemporaire.com', 'crapmail.org', 'cust.in', 'cuvox.de', 'd3p.de', 'dacoolest.com', 
  'dandikmail.com', 'dayrep.com', 'dcemail.com', 'deadaddress.com', 'deadspam.com', 
  'despammed.com', 'devnullmail.com', 'dfgh.net', 'digitalsanctuary.com', 'dingbone.com', 
  'discardmail.com', 'discardmail.de', 'disposableaddress.com', 'disposableemailaddresses.com', 
  'disposableinbox.com', 'dispose.it', 'disposeamail.com', 'disposemail.com', 'dispostable.com', 
  'dm.w3internet.co.uk', 'dodgeit.com', 'dodgit.com', 'donemail.ru', 'dontreg.com', 
  'dontsendmespam.de', 'drdrb.net', 'dump-email.info', 'dumpandjunk.com', 'dumpmail.de', 
  'dumpyemail.com', 'e-mail.com', 'e-mail.org', 'e4ward.com', 'einrot.com', 'eintagsmail.de', 
  'email-fake.com', 'email.edu', 'email60.com', 'emaildienst.de', 'emailgo.de', 'emailias.com', 
  'emailigo.de', 'emailinfive.com', 'emailmiser.com', 'emailsensei.com', 'emailtemporario.com.br', 
  'emailto.de', 'emailwarden.com', 'emailx.at.hm', 'emailxfer.com', 'emeil.in', 'emeil.ir', 
  'emz.net', 'enterto.com', 'ephemail.net', 'etranquil.com', 'etranquil.net', 'etranquil.org', 
  'explodemail.com', 'eyepaste.com', 'fakeinbox.com', 'fakeinformation.com', 'fakemail.fr', 
  'fakemailgenerator.com', 'fakemailz.com', 'fammix.com', 'fastacura.com', 'fastchevy.com', 
  'fastchrysler.com', 'fastkawasaki.com', 'fastmazda.com', 'fastmitsubishi.com', 'fastnissan.com', 
  'fastsubaru.com', 'fastsuzuki.com', 'fasttoyota.com', 'fastyamaha.com', 'filzmail.com', 
  'fizmail.com', 'fleckens.hu', 'fr33mail.info', 'frapmail.com', 'freundin.ru', 'fuckingduh.com', 
  'fudgerub.com', 'fyii.de', 'garliclife.com', 'gishpuppy.com', 'gmial.com', 'goemailgo.com', 
  'gotmail.com', 'gotmail.net', 'gotmail.org', 'gotti.rocks', 'guerillamail.biz', 'guerillamail.com', 
  'guerillamail.de', 'guerillamail.net', 'guerillamail.org', 'guerrillamail.biz', 'guerrillamail.com', 
  'guerrillamail.de', 'guerrillamail.info', 'guerrillamail.net', 'guerrillamail.org', 
  'h.mintemail.com', 'h8s.org', 'haltospam.com', 'hatespam.org', 'hidemail.de', 'hidemyass.com', 
  'hochsitze.com', 'hot-mail.cf', 'hot-mail.ga', 'hot-mail.gq', 'hot-mail.ml', 'hot-mail.tk', 
  'hotpop.com', 'hulapla.de', 'hush.com', 'hushmail.com', 'ieatspam.eu', 'ieatspam.info', 
  'iheartspam.org', 'imails.info', 'inbax.tk', 'inbox.si', 'inbox2.info', 
  'inboxalias.com', 'inboxclean.com', 'inboxclean.org', 'incognitomail.com', 'incognitomail.net', 
  'incognitomail.org', 'infocom.zp.ua', 'insorg-mail.info', 'instant-mail.de', 'ipoo.org', 
  'irish2me.com', 'iwi.net', 'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org', 
  'jnxjn.com', 'jourrapide.com', 'junk1e.com', 'junkmail.com', 'junkmail.ga', 'kasmail.com', 
  'kaspop.com', 'keepmymail.com', 'killmail.com', 'killmail.net', 'kir.ch.tc', 'klassmaster.com', 
  'klassmaster.net', 'klzlk.com', 'kulturbenoete.com', 'kurzepost.de', 'l33r.com', 'lak.pp.ua', 
  'letthemeatspam.com', 'lhsdv.com', 'lifebyfood.com', 'link2mail.net', 'litedrop.com', 
  'lol.ovpn.to', 'lolfreak.net', 'lookugly.com', 'lopl.co.cc', 'lortemail.dk', 'lr78.com', 
  'm21.cc', 'mail-filter.com', 'mail-temporaire.fr', 'mail.by', 'mail.mezimages.net', 
  'mail.svenz.eu', 'mail.ticket-please.ga', 'mail.zp.ua', 'mail1a.de', 'mail21.cc', 'mail2rss.org', 
  'mail333.com', 'mail4trash.com', 'mailbidon.com', 'mailblocks.com', 'mailbucket.org', 
  'mailcat.biz', 'mailcatch.com', 'mailde.de', 'mailde.info', 'maildrop.cc', 'maileater.com', 
  'mailexpire.com', 'mailf5.com', 'mailfa.tk', 'mailfall.com', 'mailforspam.com', 'mailfree.ga', 
  'mailfree.gq', 'mailfree.ml', 'mailfreeonline.com', 'mailguard.me', 'mailin8r.com', 
  'mailinater.com', 'mailinator.com', 'mailinator.net', 'mailinator.org', 'mailinator2.com', 
  'mailincubator.com', 'mailismagic.com', 'mailme.com', 'mailme.lv', 'mailme24.com', 
  'mailmetrash.com', 'mailmoat.com', 'mailms.com', 'mailnator.com', 'mailnesia.com', 
  'mailnull.com', 'mailorg.org', 'mailpick.biz', 'mailrock.biz', 'mailscrap.com', 
  'mailshell.com', 'mailsiphon.com', 'mailtemp.info', 'mail-tester.com', 'mailtothis.com', 
  'mailtrash.net', 'mailtv.net', 'mailzilla.com', 'mailzilla.org', 'makemetheking.com', 
  'manybrain.com', 'mbx.cc', 'mega.zik.dj', 'meinspamschutz.de', 'meltmail.com', 'messagebeamer.de', 
  'mezimages.net', 'mierdamail.com', 'migumail.com', 'ministryofspam.com', 'mintemail.com', 
  'misterpinball.de', 'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf', 'msa.minsmail.com', 
  'mt2009.com', 'mt2014.com', 'mx0.wwwnew.eu', 'mycard.net.ua', 'mycleaninbox.net', 'myemaildomain.com', 
  'mymail-in.net', 'mypacks.net', 'mypartyclip.de', 'myphantomemail.com', 'myspaceinc.com', 
  'myspaceinc.net', 'myspaceinc.org', 'myspacepimpedup.com', 'myspamless.com', 'mytempemail.com', 
  'mytrashmail.com', 'nabuma.com', 'neomailbox.com', 'nepwk.com', 'nervmich.net', 'nervtmich.net', 
  'netmails.com', 'netmails.net', 'netzidiot.de', 'neverbox.com', 'nevermail.de', 'nice-4u.com', 
  'nincsmail.hu', 'nnh.com', 'no-spam.ws', 'nobulk.com', 'noclickemail.com', 'nogmailspam.info', 
  'nomail.pw', 'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com', 'nospam.ze.tc', 
  'nospam4.us', 'nospamfor.us', 'nospamthanks.info', 'notmailinator.com', 'nowmymail.com', 
  'nurfuerspam.de', 'nus.edu.sg', 'nwldx.com', 'objectmail.com', 'obobbo.com', 'odnorazovoe.ru', 
  'oneoffemail.com', 'onewaymail.com', 'onlatedotcom.info', 'online.ms', 'opayq.com', 
  'ordinaryamerican.net', 'otherinbox.com', 'ovpn.to', 'owlpic.com', 'pancakemail.com', 
  'pcusers.otherinbox.com', 'pimpedupmyspace.com', 'pjjkp.com', 'plexolan.de', 'poczta.onet.pl', 
  'politiker-ci.de', 'polyfa.com', 'poofy.org', 'pookmail.com', 'privacy.net', 'privatdemail.net', 
  'privy-mail.com', 'privy-mail.de', 'privymail.de', 'proxymail.eu', 'prtnx.com', 'putthisinyourspamdatabase.com', 
  'qq.com', 'quickinbox.com', 'rcpt.at', 'reallymymail.com', 'recode.me', 'recursor.net', 
  'regbypass.com', 'regbypass.comsafe-mail.net', 'rejectmail.com', 'rhyta.com', 'rklips.com', 
  'rmq.fr', 'royal.net', 'rppkn.com', 'rtrtr.com', 's0ny.net', 'safe-mail.net', 'safersignup.de', 
  'safetymail.info', 'safetypost.de', 'sandelf.de', 'saynotospam.com', 'schafmail.de', 
  'schrott-email.de', 'secretemail.de', 'secure-mail.biz', 'selfdestructingmail.com', 
  'sendspamhere.com', 'senseless-entertainment.com', 'shared-mail.com', 'sharedmailbox.org', 
  'sharklasers.com', 'shieldemail.com', 'shiftmail.com', 'shitmail.me', 'shitware.nl', 
  'shmeriously.com', 'shortmail.net', 'sibmail.com', 'sinnlos-mail.de', 'skeefmail.com', 
  'slapsfromlastnight.com', 'slaskpost.se', 'smashmail.de', 'smellfear.com', 'snakemail.com', 
  'sneakemail.com', 'sofimail.com', 'sofort-mail.de', 'sogetthis.com', 'soodonims.com', 
  'spam.la', 'spam.su', 'spam4.me', 'spamail.de', 'spamarrest.com', 'spambob.com', 
  'spambob.net', 'spambob.org', 'spambog.com', 'spambog.de', 'spambog.ru', 'spambox.info', 
  'spambox.irishspringrealty.com', 'spambox.us', 'spamcannon.com', 'spamcannon.net', 
  'spamcero.com', 'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com', 'spamcowboy.net', 
  'spamcowboy.org', 'spamday.com', 'spamex.com', 'spamfree.eu', 'spamfree24.com', 'spamfree24.de', 
  'spamfree24.eu', 'spamfree24.info', 'spamfree24.net', 'spamfree24.org', 'spamgoes.in', 
  'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org', 'spamherelots.com', 'spamhereplease.com', 
  'spamhole.com', 'spamify.com', 'spaminator.de', 'spamkill.info', 'spaml.com', 'spaml.de', 
  'spammotel.com', 'spamobox.com', 'spamoff.de', 'spamslicer.com', 'spamspot.com', 
  'spamstack.net', 'spamthis.co.uk', 'spamthisplease.com', 'spamtrail.com', 'spamtroll.net', 
  'speed.1s.fr', 'spoofmail.de', 'squizzy.de', 'srtr.com', 'startkeys.com', 'stuffmail.de', 
  'sudolife.me', 'sudolife.net', 'sudomail.com', 'sudomail.net', 'sudouser.net', 'super-auswahl.de', 
  'supergreatmail.com', 'supermailer.jp', 'superrito.com', 'superstachel.de', 'suremail.info', 
  't.psh.me', 'teewars.org', 'teleworm.com', 'teleworm.us', 'temp-mail.org', 'temp-mail.ru', 
  'tempe-mail.com', 'tempemail.co.za', 'tempemail.com', 'tempemail.net', 'tempinbox.co.uk', 
  'tempinbox.com', 'tempmail.eu', 'tempmail.it', 'tempmail.us', 'tempmail2.com', 'tempmaildemo.com', 
  'tempmailer.com', 'tempmailer.de', 'tempomail.fr', 'temporarily.de', 'temporarioemail.com.br', 
  'temporaryemail.net', 'temporaryforwarding.com', 'temporaryinbox.com', 'temporarymailaddress.com', 
  'tempr.email', 'thanksnospam.info', 'thankyou2010.com', 'thisisnotmyrealemail.com', 'throwawayemailaddress.com', 
  'tilien.com', 'tittbit.in', 'tizi.com', 'tmail.com', 'tmailinator.com', 'toomail.biz', 'tradermail.info', 
  'trash-mail.at', 'trash-mail.com', 'trash-mail.de', 'trash2009.com', 'trashdevil.com', 
  'trashemail.de', 'trashmail.at', 'trashmail.com', 'trashmail.de', 'trashmail.me', 'trashmail.net', 
  'trashmail.org', 'trashymail.com', 'trialmail.de', 'trillianpro.com', 'turual.com', 'twinmail.de', 
  'tyldd.com', 'uggsrock.com', 'umail.net', 'upliftnow.com', 'uplipht.com', 'venompen.com', 
  'veryrealemail.com', 'vidchart.com', 'vmail.me', 'vomoto.com', 'vpn.st', 'vsimcard.com', 
  'vubby.com', 'wasteland.rfc822.org', 'webemail.me', 'webmell.com', 'weg-werf-email.de', 
  'wegwerf-email-addressen.de', 'wegwerf-email.at', 'wegwerf-email.de', 'wegwerf-emails.de', 
  'wegwerfadresse.de', 'wegwerfemail.com', 'wegwerfemail.de', 'wegwerfemail.net', 'wegwerfemail.org', 
  'wegwerfemailadresse.com', 'wegwerfmail.de', 'wegwerfmail.info', 'wegwerfmail.net', 'wegwerfmail.org', 
  'wetrainbayarea.com', 'wetrainbayarea.org', 'wh4f.org', 'whatpaas.com', 'whatsaas.com', 
  'whopy.com', 'whtjddn.com', 'whyspam.me', 'willhackforfood.biz', 'willselfdestruct.com', 
  'winemaven.info', 'wronghead.com', 'wuzup.net', 'wuzupmail.net', 'www.e4ward.com', 'www.gishpuppy.com', 
  'www.mailinator.com', 'wwwnew.eu', 'xagloo.com', 'xemaps.com', 'xents.com', 'xmaily.com', 
  'xoxy.net', 'yep.com', 'yogamaven.com', 'yopmail.com', 'yopmail.fr', 'yopmail.net', 
  'yourdomain.com', 'ypmail.webarnak.fr.eu.org', 'yuurok.com', 'z1p.biz', 'za.com', 'zehnminutenmail.de', 
  'zeta-telecom.com', 'zippymail.info', 'zomg.info', 'zxcv.com', 'zxcvbnm.com', 'zzz.com',
  // Added from another common list
  'mail.tm', 'mailinator.co.uk', 'mailinator.info', 'mailinator.us', 'tempmail.com', '10minemail.com',
  'guerrillamail.block', 'maildrop.cc', 'temp-mail.io', 'yopmail.net', 'throwawaymail.com',
  'tempmail.dev', 'tempmail.alt.za', 'temp-mail.de', 'mailtemporaire.fr', 'tempmail.live',
  'mailpoof.com', 'trashmail.com', 'mailinator.net', 'temp-mail.address', 'emltmp.com',
  'disposable.ml', 'disposable.cf', 'disposable.ga', 'disposable.gq', 'tempmail.ws', 'mohmal.com',
  '10minutemail.net', 'emailondeck.com', 'getnada.com', 'guerrillamail.info', 'tempmail.org'
];

// Block TLDs commonly used for spam or temporary services
export const blockedTlds = [
  'xyz', 'icu', 'buzz', 'top', 'click', 'monster', 'live', 'site', 'online', 'loan', 'work', 'gq'
];
